### ISSUE TITLE
Print Manager in Android

### ISSUE THREAD

**Issue by DineshkumarDevarasu** [johnjohndoe/Android-Developers-Samples#3]
In my android application, I have an option to print the invoices for the delivery order. I am generating the Invoice content as html and sending it to android print manager as a string to print it. It is getting opened in print dialog and I am able to select a printer for printing. But after the print, my application is getting closed. But I want to redirect to the same page after the print.

Also I want to set the number of copies to 2 while printing programmatically from the android print manager. This is my source code.

 private void print() {
        // Create a WebView and hold on to it as the printing will start when
        // load completes and we do not want the WbeView to be garbage collected.
        mWebView = new WebView(this);

        // Important: Only after the page is loaded we will do the print.
        mWebView.setWebViewClient(new WebViewClient() {
            @RequiresApi(api = Build.VERSION_CODES.KITKAT)
            @Override
            public void onPageFinished(WebView view, String url) {
                doPrint();
            }
        });

        mWebView.loadDataWithBaseURL(null, htmlDocument, "text/HTML", "UTF-8", null);

        // Load an HTML page.
        //  mWebView.loadUrl("file:///android_res/raw/motogp_stats.html");
    }

    @RequiresApi(api = Build.VERSION_CODES.KITKAT)
    private void doPrint() {

        // Get the print manager.
        PrintManager printManager = (PrintManager) getSystemService(
                Context.PRINT_SERVICE);

       // Create a wrapper PrintDocumentAdapter to clean up when done.
        PrintDocumentAdapter adapter = new PrintDocumentAdapter() {
            private final PrintDocumentAdapter mWrappedInstance =
                    mWebView.createPrintDocumentAdapter();

            @Override
            public void onStart() {
                mWrappedInstance.onStart();
            }

            @Override
            public void onLayout(PrintAttributes oldAttributes, PrintAttributes newAttributes,
                                 CancellationSignal cancellationSignal, LayoutResultCallback callback,
                                 Bundle extras) {
                mWrappedInstance.onLayout(oldAttributes, newAttributes, cancellationSignal,
                        callback, extras);
            }

            @Override
            public void onWrite(PageRange[] pages, ParcelFileDescriptor destination, CancellationSignal cancellationSignal, WriteResultCallback callback) {
                mWrappedInstance.onWrite(pages, destination, cancellationSignal, callback);
            }

            @Override
            public void onFinish() {
                mWrappedInstance.onFinish();
                // Intercept the finish call to know when printing is done
                // and destroy the WebView as it is expensive to keep around.
                mWebView.destroy();
                mWebView = null;
            }
        };

        try{
            // Pass in the ViewView's document adapter.
           printManager.print("MotoGPstats", adapter, null);
           // printManager.print("MotoGP stats", mWebView.createPrintDocumentAdapter(), null);
            Log.i("MotoGPstats",""+mWebView.createPrintDocumentAdapter());
            Log.i("printtest",""+adapter);
        }catch (NullPointerException n){
            n.getMessage();
        }

    }

**Comment by johnjohndoe** [comment]
@DineshkumarDevarasu First of all I have to tell you that I created this repository just for the purpose of tracking changes being made to the sample project by Google. Therefore, here is no room for issues. No offense please.

Nonetheless, if you have your project open source I might have the time to take a look at the issue. Please link it here.
